### PR TITLE
Remove automerge

### LINKED ISSUE #41: Deps are all wrong - need to enable grayskull inspection
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/mkdocs-feedstock/blob/b9283407afb7a47b3c1c25ade3d68c894efa66a4/recipe/meta.yaml#L22-L33

https://github.com/mkdocs/mkdocs/blame/1.4.0/setup.py#L66-L78

https://github.com/conda-forge/mkdocs-feedstock/blob/b9283407afb7a47b3c1c25ade3d68c894efa66a4/conda-forge.yml#L1-L2

```yaml
bot:
  automerge: true
  inspection: update-grayskull
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #41

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Thanks @ocefpaf! I meant that issue as more of a note to my future-self rather than a request for someone else to fix it. Thanks for sorting it out though! :heart:

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf! I meant that issue as more of a note to my future-self rather than a request for someone else to fix it. Thanks for sorting it out though! heart

NP. Lately automerge has been doing more harm than good and I'm removing it from all the feedstocks I maintain. At least util we get full grayskull recipe regeneration.

**Comment by xhochy** [comment]
@ocefpaf https://github.com/conda-forge/pdm-feedstock/blob/dd842cae663a1f3aea5635e59f3963b43b52fa83/conda-forge.yml#L3 has been working like a charm for me in the last months.

**Comment by ocefpaf** [comment]
> @ocefpaf https://github.com/conda-forge/pdm-feedstock/blob/dd842cae663a1f3aea5635e59f3963b43b52fa83/conda-forge.yml#L3 has been working like a charm for me in the last months.

Yep. I'm adding that to all the feedstocks I can. I forget sometimes. (I'm the one fighting for that functionality for years now :-)

**Pull request merged**
