### PR TITLE
Bump version to 1.2.4

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm unsure of the error in #33 so thought I'd put in a PR to release this version since I don't *need* 1.3.0. I'm just wanting to grab the `jinja2` fix - https://github.com/mkdocs/mkdocs/issues/2799#issuecomment-1079764329

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/mkdocs/mkdocs/blame/1.2.4/setup.py#L60-L71

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
ping @ocefpaf - if you've got time it would be great to get this merged to avoid issues with the latest `jinja2` version.

**Comment by hadim** [comment]
I am also seeing the jinja issue.

**Comment by dhirschfeld** [comment]
Thanks @ocefpaf!

**Pull request merged**
